/**
 * config.js
 */

module.exports = {
  server: {
    port: process.env.QW_PORT || 3040,
  },
  minify: {
    enable: false,
    options: {
      includeAutoGeneratedTags: true,
      removeAttributeQuotes: false,
      removeComments: true,
      removeRedundantAttributes: false,
      removeScriptTypeAttributes: true,
      removeStyleLinkTypeAttributes: true,
      sortClassName: true,
      useShortDoctype: true,
      collapseWhitespace: true,
    },
  },
};
